const GET_CATEGORIES= 'GET_CATEGORIES';
const POST_CATEGORY= 'POST_CATEGORY';
const DELETE_CATEGORY= 'DELETE_CATEGORY';
const FIND_CATEGORY= 'FIND_CATEGORY';

export { GET_CATEGORIES, POST_CATEGORY, DELETE_CATEGORY, FIND_CATEGORY };