const NEW_PRODUCT = 'NEW_PRODUCT';
const LIST_PRODUCTS = 'LIST_PRODUCTS';
const SINGLE_PRODUCT ='SINGLE_PRODUCT'
const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY'
export {NEW_PRODUCT, LIST_PRODUCTS, SINGLE_PRODUCT, FILTER_BY_CATEGORY} ;



            