const NEW_PRODUCT = 'NEW_PRODUCT';
const LIST_PRODUCTS = 'LIST_PRODUCTS';
const SINGLE_PRODUCT ="SINGLE_PRODUCT"
const EDIT_PRODUCT= 'EDIT_PRODUCT';
const HANDLE_EDIT= 'HANDLE_EDIT';
const INCLUDE_CATEGORIES= 'INCLUDE_CATEGORIES';
const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY'
export { NEW_PRODUCT, LIST_PRODUCTS, SINGLE_PRODUCT, EDIT_PRODUCT, HANDLE_EDIT, INCLUDE_CATEGORIES,FILTER_BY_CATEGORY } ;



            